# Generated by Django 3.2.11 on 2025-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(default=-1)),
                ('roomID', models.IntegerField(default=-1)),
                ('submitTime', models.DateTimeField(default='2000-01-01 00:00')),
            ],
        ),
    ]
