# Generated by Django 3.2.11 on 2025-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20250302_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='managerID',
            field=models.IntegerField(default=-1),
        ),
    ]
