# Generated by Django 3.2.11 on 2025-03-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_order_managerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finishTime',
            field=models.DateTimeField(default='2000-01-01 00:00'),
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
