# Generated by Django 3.2.11 on 2025-03-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20250309_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assignTime',
            field=models.DateTimeField(default='2000-01-01 00:00'),
        ),
    ]
