# Generated by Django 3.2.11 on 2025-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.AutoField(primary_key=True, serialize=False)),
                ('rentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rentId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('roomId', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('applyTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.IntegerField(null=True)),
                ('email', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
