# Generated by Django 3.2.11 on 2025-03-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='roomId',
            field=models.IntegerField(default=0),
        ),
    ]
