# Generated by Django 3.2.11 on 2025-03-08 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
