# Generated by Django 3.2.11 on 2025-03-08 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bill_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
