# Generated by Django 3.2.11 on 2025-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('knowledgeId', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=100)),
                ('solution', models.TextField(max_length=2000)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
