# Generated by Django 3.2.11 on 2025-03-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='type',
        ),
    ]
